### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by saulocurty** [namishh/dwm#1]
I really like your config and would like to understand better how you did it. Would you be able to make a mini documentation about this repository? I made my first DWM config today on a humbler pc and I liked how yours turned out.

**Comment by siduck** [comment]
@saulocurty seems like chadcat doesnt use dwm anymore. In case you can try mine as it looks better & has lil documentation, eww widgets provided too

https://github.com/siduck/chadwm

**Comment by namishh** [comment]
As I do not have much C knowledge myself, I will not be able to document things that effectively. But for the eww widgets, you can visit this commit.

https://github.com/chadcat7/crystal/tree/0f333e1bd478ac67c06c66d8c6877b4c1cc19144/
